# Build the pdf

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-extra texlive-lang-german
      - name: Build the pdf from latex source
        run: make --directory=src
